### ISSUE TITLE
Confusing instructions on answer page

### ISSUE THREAD

**Issue by gdevenyi** [DouglasNeuroInformatics/PictureNamingTask#8]
![image](https://github.com/user-attachments/assets/2a172bcb-c0f4-48bf-aca7-03d568eb9a6e)

"Press any key to submit the response" doesn't work for and is confusing considering the "Continue" button also present.

**Comment by CMonnin** [comment]
fixed in commit d6ca14b

**Comment by gdevenyi** [comment]
This bug is in the current demo.

**Comment by CMonnin** [comment]
commit d6ca14b has been pushed and resolved the issue. The demo has the new wording
